apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tobira-models
  namespace: tobira
  labels:
    app.kubernetes.io/name: tobira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
