# tobira module configuration
# Local overrides can be placed in local.d/tobira.conf

tobira {
  enabled = false;
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/tobira.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/tobira.conf"
}
