"""Knowledge distillation pipeline.

Transfer knowledge from large teacher models to smaller student models.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from tobira.backends.protocol import BackendProtocol, PredictionResult

logger = logging.getLogger(__name__)


def _import_deps() -> tuple:
    """Lazily import torch and transformers."""
    try:
        import torch
        from transformers import (
            AutoModelForSequenceClassification,
            AutoTokenizer,
            TrainingArguments,
        )
    except ImportError as exc:
        raise ImportError(
            "torch and transformers are required for knowledge distillation. "
            "Install them with: pip install tobira[bert]"
        ) from exc
    return torch, AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments


@dataclass(frozen=True)
class SoftLabel:
    """Soft label generated by a teacher model.

    Attributes:
        text: The input text.
        labels: Probability distribution over classes from the teacher.
    """

    text: str
    labels: dict[str, float]


@dataclass(frozen=True)
class DistillationResult:
    """Result of a distillation run.

    Attributes:
        teacher_name: Name/type of the teacher backend.
        student_model_name: HuggingFace model name of the student.
        output_path: Path where the distilled model was saved.
        num_samples: Number of training samples used.
        temperature: Temperature used for distillation.
        alpha: Weight for soft label loss vs hard label loss.
        epochs: Number of training epochs completed.
    """

    teacher_name: str
    student_model_name: str
    output_path: str
    num_samples: int
    temperature: float
    alpha: float
    epochs: int


@dataclass
class DistillationConfig:
    """Configuration for knowledge distillation.

    Attributes:
        student_model_name: HuggingFace model name for the student model.
        temperature: Softmax temperature for distillation. Higher values
            produce softer probability distributions. Defaults to 3.0.
        alpha: Weight for soft label (KD) loss. The hard label loss weight
            is ``(1 - alpha)``. Defaults to 0.7.
        epochs: Number of training epochs. Defaults to 5.
        batch_size: Training batch size. Defaults to 16.
        learning_rate: Learning rate for the student optimizer. Defaults to 5e-5.
        max_length: Maximum token sequence length. Defaults to 512.
        device: Device string (e.g. ``"cpu"``, ``"cuda"``). When *None*,
            automatically selects CUDA if available.
    """

    student_model_name: str = "distilbert-base-uncased"
    temperature: float = 3.0
    alpha: float = 0.7
    epochs: int = 5
    batch_size: int = 16
    learning_rate: float = 5e-5
    max_length: int = 512
    device: str | None = None
    label_names: list[str] = field(default_factory=lambda: ["ham", "spam"])


def generate_soft_labels(
    teacher: BackendProtocol,
    texts: list[str],
) -> list[SoftLabel]:
    """Generate soft labels from a teacher backend.

    Uses the teacher's ``predict()`` method to produce probability
    distributions over classes for each input text.

    Args:
        teacher: A backend implementing BackendProtocol (e.g. BertBackend).
        texts: List of input texts to label.

    Returns:
        List of SoftLabel instances with teacher predictions.

    Raises:
        ValueError: If texts is empty.
    """
    if not texts:
        raise ValueError("texts must not be empty")

    soft_labels: list[SoftLabel] = []
    for i, text in enumerate(texts):
        result: PredictionResult = teacher.predict(text)
        soft_labels.append(SoftLabel(text=text, labels=result.labels))
        if (i + 1) % 100 == 0:
            logger.info("Generated soft labels: %d / %d", i + 1, len(texts))

    logger.info("Soft label generation complete: %d samples", len(soft_labels))
    return soft_labels


def save_soft_labels(soft_labels: list[SoftLabel], path: str | Path) -> Path:
    """Save soft labels to a JSONL file.

    Args:
        soft_labels: List of SoftLabel instances.
        path: Output file path.

    Returns:
        Path to the saved file.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for sl in soft_labels:
            record = {"text": sl.text, "labels": sl.labels}
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    logger.info("Saved %d soft labels to %s", len(soft_labels), path)
    return path


def load_soft_labels(path: str | Path) -> list[SoftLabel]:
    """Load soft labels from a JSONL file.

    Args:
        path: Path to the JSONL file.

    Returns:
        List of SoftLabel instances.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Soft labels file not found: {path}")

    soft_labels: list[SoftLabel] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                record = json.loads(line)
                soft_labels.append(
                    SoftLabel(text=record["text"], labels=record["labels"])
                )
    logger.info("Loaded %d soft labels from %s", len(soft_labels), path)
    return soft_labels


def distill(
    soft_labels: list[SoftLabel],
    output_path: str | Path,
    config: DistillationConfig | None = None,
    teacher_name: str = "unknown",
) -> DistillationResult:
    """Train a student model using knowledge distillation.

    The student model is fine-tuned using a combination of:
    - KL divergence loss against the teacher's soft labels (weighted by alpha)
    - Cross-entropy loss against hard labels (weighted by 1 - alpha)

    Args:
        soft_labels: Soft labels generated by the teacher model.
        output_path: Directory to save the distilled student model.
        config: Distillation configuration. Uses defaults if None.
        teacher_name: Name of the teacher backend for reporting.

    Returns:
        DistillationResult with training metadata.

    Raises:
        ValueError: If soft_labels is empty or label_names do not match.
        ImportError: If torch or transformers are not installed.
    """
    if not soft_labels:
        raise ValueError("soft_labels must not be empty")

    if config is None:
        config = DistillationConfig()

    torch, AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments = (
        _import_deps()
    )

    output_path = Path(output_path)
    output_path.mkdir(parents=True, exist_ok=True)

    if config.device is None:
        device_str = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        device_str = config.device
    device = torch.device(device_str)

    label_names = config.label_names
    num_labels = len(label_names)
    label2id = {name: i for i, name in enumerate(label_names)}
    id2label = {i: name for i, name in enumerate(label_names)}

    # Load student model and tokenizer
    logger.info("Loading student model: %s", config.student_model_name)
    tokenizer = AutoTokenizer.from_pretrained(config.student_model_name)
    student = AutoModelForSequenceClassification.from_pretrained(
        config.student_model_name,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True,
    )
    student.to(device)
    student.train()

    # Prepare training data
    texts = [sl.text for sl in soft_labels]
    teacher_distributions = []
    hard_labels_list = []
    for sl in soft_labels:
        dist = [sl.labels.get(name, 0.0) for name in label_names]
        teacher_distributions.append(dist)
        hard_labels_list.append(int(dist[1] >= 0.5) if num_labels == 2 else 0)

    teacher_tensor = torch.tensor(teacher_distributions, dtype=torch.float32)
    hard_labels_tensor = torch.tensor(hard_labels_list, dtype=torch.long)

    # Tokenize
    encodings = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=config.max_length,
        return_tensors="pt",
    )

    # Training loop
    optimizer = torch.optim.AdamW(student.parameters(), lr=config.learning_rate)
    dataset_size = len(texts)
    batch_size = min(config.batch_size, dataset_size)

    logger.info(
        "Starting distillation: %d samples, %d epochs, batch_size=%d",
        dataset_size,
        config.epochs,
        batch_size,
    )

    for epoch in range(config.epochs):
        total_loss = 0.0
        num_batches = 0

        indices = torch.randperm(dataset_size)

        for start in range(0, dataset_size, batch_size):
            end = min(start + batch_size, dataset_size)
            batch_idx = indices[start:end]

            batch_inputs: dict[str, Any] = {
                k: v[batch_idx].to(device) for k, v in encodings.items()
            }
            batch_teacher = teacher_tensor[batch_idx].to(device)
            batch_hard = hard_labels_tensor[batch_idx].to(device)

            outputs = student(**batch_inputs)
            student_logits = outputs.logits

            # KD loss: KL divergence between teacher and student soft distributions
            log_softmax = torch.nn.functional.log_softmax
            softmax = torch.nn.functional.softmax

            T = config.temperature
            student_log_probs = log_softmax(student_logits / T, dim=-1)
            teacher_probs = softmax(
                torch.log(batch_teacher.clamp(min=1e-8)) / T, dim=-1
            )

            kd_loss = torch.nn.functional.kl_div(
                student_log_probs,
                teacher_probs,
                reduction="batchmean",
            ) * (T * T)

            # Hard label loss: standard cross-entropy
            ce_loss = torch.nn.functional.cross_entropy(student_logits, batch_hard)

            # Combined loss
            loss = config.alpha * kd_loss + (1.0 - config.alpha) * ce_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += float(loss)
            num_batches += 1

        avg_loss = total_loss / max(num_batches, 1)
        logger.info("Epoch %d/%d - loss: %.4f", epoch + 1, config.epochs, avg_loss)

    # Save model
    student.save_pretrained(str(output_path))
    tokenizer.save_pretrained(str(output_path))
    logger.info("Distilled model saved to %s", output_path)

    return DistillationResult(
        teacher_name=teacher_name,
        student_model_name=config.student_model_name,
        output_path=str(output_path),
        num_samples=dataset_size,
        temperature=config.temperature,
        alpha=config.alpha,
        epochs=config.epochs,
    )
