apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tobira-api
  labels:
    app: tobira
    component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tobira-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
