apiVersion: v1
kind: Service
metadata:
  name: tobira-api
  labels:
    app: tobira
    component: api
spec:
  type: ClusterIP
  selector:
    app: tobira
    component: api
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
